### ISSUE TITLE
Advanced setup links don't work

### ISSUE THREAD

**Issue by danstans** [nativescript-vue/nativescript-vue.org#11]
Trying to setup my linux machine for development but the advanced setup links on [this page](https://nativescript-vue.org/#/installation-nativescript) are broken. Is it possible that they are supposed to reference these links instead? 

- [Mac setup](https://docs.nativescript.org/start/ns-setup-os-x)
- [Linux setup](https://docs.nativescript.org/start/ns-setup-linux)
- [Windows setup](https://docs.nativescript.org/start/ns-setup-win)

**Comment by rigor789** [comment]
Hi, yes those links are indeed broken because the docs are auto-generated based on the official docs, and thus the links are completely wrong. This repository is actually a brand new site that will be live soon, without this issue, so I'm closing this one. In the meantime you can browse around the new site here: https://nativescript-vue.netlify.com/

but since it's a WIP there are a few missing pieces.
